server:
  port: 8082
  servlet:
    context-path: /api-pagamento

spring:
  application:
    name: pagamentos
  datasource:
    url: jdbc:mariadb://localhost:3306/pagamento?createDatabaseIfNotExist=true
    username: root
    password: admin
    driverClassName: org.hibernate.dialect.MariaDB10Dialect

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jmx:
    enabled: false