server:
  port: 8083
  servlet:
    context-path: /autenticacao

spring:
  application:
    name: autenticacao
  datasource:
    url: jdbc:mariadb://localhost:3306/autenticacao?createDatabaseIfNotExist=true
    username: root
    password: admin
    driverClassName: org.hibernate.dialect.MariaDB10Dialect
 
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jmx:
    enabled: false
security:
  jwt:
    token:
      secret-key: chave-microservice
      expired: 36000