server:  port: 8081  servlet:    context-path: /api-produto

spring:  application:    name: produtos
  datasource:
    url: jdbc:mariadb://localhost:3306/produto?createDatabaseIfNotExist=true
    username: root
    password: admin
    driverClassName: org.hibernate.dialect.MariaDB10Dialect

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update  jmx:    enabled: false  rabbitmq:    host: localhost    port: 5672    username: admin    password: adminproduto:  rabbitmq:    exchange: produto.exchange    routingkey: produto.routingkey